# vim:ts=2:sw=2:et
dist: precise

language: php

services:
  - postgresql

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_install:
  - echo 'en_US.UTF-8 UTF-8' | sudo tee --append /var/lib/locales/supported.d/local
  - echo 'cs_CZ.UTF-8 UTF-8' | sudo tee --append /var/lib/locales/supported.d/local
  - sudo locale-gen
  - locale -a
  - composer global require "phpunit/phpunit=4.8.*"
  - git submodule init && git submodule update
  - ./scripts/check_system || echo "FIX REQUIREMENTS!"

before_script:
  - travis_retry composer install --dev --no-interaction --prefer-dist
  - echo "y" | ATK14_ENV=test ./scripts/create_database
  - ATK14_ENV=test ./scripts/migrate

script:
  - ./scripts/run_all_tests && echo "EVERYTHING IS FINE"
