# vim:ts=2:sw=2:et
os: linux

# Partner Queue Solution, no credits are consumed
arch: ppc64le

language: php

services:
  - postgresql

jobs:
  include:
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: xenial
    - php: 7.2
      dist: xenial
    - php: 7.3
      dist: xenial
    - php: 7.4
      dist: xenial
    - php: 8.0
      dist: focal
    - php: 8.1
      dist: focal

before_install:
  - sudo locale-gen en_US.UTF-8
  - sudo locale-gen cs_CZ.UTF-8
  - sudo update-locale
  - locale -a
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"
  - git submodule init && git submodule update
  - ./scripts/check_system || echo "FIX SYSTEM REQUIREMENTS!"

before_script:
  - travis_retry composer install --dev --no-interaction --prefer-dist
  - echo "y" | ATK14_ENV=test ./scripts/create_database
  - echo "SELECT VERSION()" | ATK14_ENV=test ./scripts/dbconsole
  - ATK14_ENV=test ./scripts/migrate
  - echo '127.0.0.1 atk14skelet.localhost' | sudo tee --append /etc/hosts
  - ./scripts/check_installation || echo "FIX APPLICATION REQUIREMENTS!"

script:
  - ./scripts/run_all_tests && echo "EVERYTHING IS FINE"
