# This is a recipe how to deploy this application to our production environment
#
# You can run the deployment process by typing
#  $ ./scripts/deploy production
#
# or just
#  $ ./scripts/deploy
#

production:
  server: "kajka"                                                           # we are deploying on this server
  user: "devel"                                                             # we are deploying as this user
  directory: "/home/devel/apps/atk14skelet/production/"                     # in this directory is this application installed on the server
  deploy_via: "git_push"                                                    # at the moment this is the only way how to deploy
  deploy_repository: "devel@kajka:apps/atk14skelet/repos/production.git"    # this is the URL of deployment git repository with a proper post-receive hook
  deploy_branch: "master"                                                   # the name of the branch in deployment repository
  rsync:
  - "public/dist/"                                                          # since the directory public/dist is ignored in .gitignore we need to synchronize it by deployment process

# You can have another stage to deploy application on it (eg. preview).
# In this recipe you can mention only items which differ from the first recipe.
#
# preview:
#   server: server.example.com
#   user: deploy
#   directory: /home/deploy/previews/atk14skelet/
#   deploy_repository: deploy@server.example.com:repos/atk14skelet.git
