# Here is the list of languages used in your application.
# The first one is the default language. The front page is beeing served in the default language.

# vim: set et:

en:
  LANG: en_US.UTF-8
  name: "english"

cs:
  LANG: cs_CZ.UTF-8
  name: "Äesky"
  fallback: "en" # for multi language objects it's possible to specify a fallback language
